---
title: Thucydidean Times
language: zh-CN
slogan: 'TODO: slogan blahblah'
description: 'TODO: description blahblah'
credits: 'Licensed under <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC-BY-NC-4.0</a>'
url: https://thucydideantimes.org
domain: thucydideantimes.org
theme: jekyll-theme-feeling-responsive
urlimg: '/assets/img/'
logo: logo.png
disqus_shortname: thucydidean-times
collections:
  dailynews:
    title: 每日新闻精选
    description: 测试描述 blahblah
    output: true
    permalink: /blog/:collection/:year/:month/:day/:title/
  echoesofcapital:
    title: 资本之声
    description: 测试描述 blahblah
    output: true
    permalink: /blog/:collection/:year/:month/:day/:title/
  yongledadian:
    title: 永乐大典
    description: 测试描述 blahblah
    output: true
    permalink: /blog/:collection/:year/:month/:day/:title/
  militarytimes:
    title: 军事时报
    description: 测试描述 blahblah
    output: true
    permalink: /blog/:collection/:year/:month/:day/:title/
exclude:
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - '.git/'
  - tmp/
pagination:
  enabled: true
  sort_field: date
  sort_reverse: true
article_assets: '/assets/articles/'
defaults:
  - scope:
      path: _articles
    values:
      layout: page
      comments: true
      breadcrumb: true
      image:
        title: placeholder.png
        caption: Placeholder image
        caption_url: https://example.com
        thumb: placeholder.png
        homepage: placeholder.png
      header:
        image_fullwidth: placeholder.png
  - scope:
      path: pages
    values:
      breadcrumb: true
      sidebar: right
      header:
        image_fullwidth: placeholder.png
